#!/usr/bin/env php
<?php
// app/console
require_once __DIR__.'/bootstrap.php';

use Symfony\Component\Console\Application;

$app = new Application();
$app->add(new \PF\EnApi\Command\Consumption);

$app->run();